<a href="https://colab.research.google.com/github/sh2624/CSE/blob/main/3_pandas_(student).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터프로그래밍

## 실습4: Pandas

In [ ]:
import numpy as np
import pandas as pd

### Series

In [ ]:
# Create a Series with [1, "John", 3.5, "Hey"]
obj = pd.Series([1, "John", 3.5, "Hey"])

print(type(obj))
print(obj)
print(obj.values)

<class 'pandas.core.series.Series'>
0       1
1    John
2     3.5
3     Hey
dtype: object
[1 'John' 3.5 'Hey']

In [ ]:
# Create a Series with [1, "John", 3.5, "Hey"]
# Indexing with ["a", "b", "c", "d"]
obj2 = pd.Series([1, "John", 3.5, "Hey"], index = ["a", "b", "c", "d"])
print(obj2)
print(obj2["b"])
print(obj2.index)

a       1
b    John
c     3.5
d     Hey
dtype: object
John
Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
# Create a Series with dictionary, {"Jane": 90, "Bill": 80, "Elon": 85,"Tom": 75, "Tim": 95}
score = {"Jane": 90, "Bill": 80, "Elon": 85,"Tom": 75, "Tim": 95 }

# Convert the given dictionary to Series
names = pd.Series(score)
print(names)
print(names["Tim"])

Jane    90
Bill    80
Elon    85
Tom     75
Tim     95
dtype: int64
95

In [ ]:
# Print data, a score is higher than 85
print(names[names > 85])

Jane    90
Tim     95
dtype: int64

In [ ]:
# Change a score of Tom with 60
names["Tom"] = 60
print(names)

Jane    90
Bill    80
Elon    85
Tom     60
Tim     95
dtype: int64

In [ ]:
# Change a score of whom is lower than 80 to 83
names[names < 80] = 83
print(names)

Jane    90
Bill    80
Elon    85
Tom     83
Tim     95
dtype: int64

### DataFrame

In [ ]:
data={"name": ["Bill", "Tom", "Tim", "John", "Alex", "Vanessa", "Kate"],
      "score": [90, 80, 85, 75, 95, 60, 65],
      "sport": ["Wrestling", "Football", "Skiing", "Swimming", "Tennis", "Karete", "Surfing"],
      "sex":["M", "M", "M", "M", "F", "F", "F"]}

In [ ]:
# Create a DataFrame using the given data
df = pd.DataFrame(data)

print(df)

      name  score      sport sex
0     Bill     90  Wrestling   M
1      Tom     80   Football   M
2      Tim     85     Skiing   M
3     John     75   Swimming   M
4     Alex     95     Tennis   F
5  Vanessa     60     Karete   F
6     Kate     65    Surfing   F

In [ ]:
# Create a DataFrame with explicit index, ["name", "sport", "sex", "score"]
df = pd.DataFrame(data, columns = ["name", "sport", "sex", "score"])

print(df)

      name      sport sex  score
0     Bill  Wrestling   M     90
1      Tom   Football   M     80
2      Tim     Skiing   M     85
3     John   Swimming   M     75
4     Alex     Tennis   F     95
5  Vanessa     Karete   F     60
6     Kate    Surfing   F     65

In [ ]:
# Print the first five rows
print(df.head())

   name      sport sex  score
0  Bill  Wrestling   M     90
1   Tom   Football   M     80
2   Tim     Skiing   M     85
3  John   Swimming   M     75
4  Alex     Tennis   F     95

In [ ]:
# Print the last five rows
print(df.tail())

      name     sport sex  score
2      Tim    Skiing   M     85
3     John  Swimming   M     75
4     Alex    Tennis   F     95
5  Vanessa    Karete   F     60
6     Kate   Surfing   F     65

In [ ]:
# Append age column on the given data
df = pd.DataFrame(data, columns = ["name", "sport", "sex", "score", "age"])

print(df)

      name      sport sex  score  age
0     Bill  Wrestling   M     90  NaN
1      Tom   Football   M     80  NaN
2      Tim     Skiing   M     85  NaN
3     John   Swimming   M     75  NaN
4     Alex     Tennis   F     95  NaN
5  Vanessa     Karete   F     60  NaN
6     Kate    Surfing   F     65  NaN

In [ ]:
# Append gender column on the given data and
# designate the index as ["one", "two", "three", "four", "five", "six", "seven"]
df = pd.DataFrame(data, columns = ["name", "sport", "sex", "score", "age"],
                  index = ["one", "two", "three", "four", "five", "six", "seven"])

print(df)

          name      sport sex  score  age
one       Bill  Wrestling   M     90  NaN
two        Tom   Football   M     80  NaN
three      Tim     Skiing   M     85  NaN
four      John   Swimming   M     75  NaN
five      Alex     Tennis   F     95  NaN
six    Vanessa     Karete   F     60  NaN
seven     Kate    Surfing   F     65  NaN

In [ ]:
# Print the column where its name is sport.
print(df["sport"])

one      Wrestling
two       Football
three       Skiing
four      Swimming
five        Tennis
six         Karete
seven      Surfing
Name: sport, dtype: object

In [ ]:
# Define name and sport columns with my_columns
# Print the column using my_columns
my_columns = ["name", "sport"]

print(df[my_columns])

          name      sport
one       Bill  Wrestling
two        Tom   Football
three      Tim     Skiing
four      John   Swimming
five      Alex     Tennis
six    Vanessa     Karete
seven     Kate    Surfing

In [ ]:
# Fill the age column with values [18, 19, 20, 18, 17, 17, 18]
values = [18, 19, 20, 18, 17, 17, 18]
df["age"] = values

print(df)

          name      sport sex  score  age
one       Bill  Wrestling   M     90   18
two        Tom   Football   M     80   19
three      Tim     Skiing   M     85   20
four      John   Swimming   M     75   18
five      Alex     Tennis   F     95   17
six    Vanessa     Karete   F     60   17
seven     Kate    Surfing   F     65   18

In [ ]:
# Make the pass column (boolean)
# If the score is greather than or equal 70, assign True (otherwise assign False)
df["pass"] = df["score"] >= 70
# df["pass"] = df.score >= 70

print(df)

          name      sport sex  score  age   pass
one       Bill  Wrestling   M     90   18   True
two        Tom   Football   M     80   19   True
three      Tim     Skiing   M     85   20   True
four      John   Swimming   M     75   18   True
five      Alex     Tennis   F     95   17   True
six    Vanessa     Karete   F     60   17  False
seven     Kate    Surfing   F     65   18  False

### Basic Functions
* Summarizing & Computing Descriptive Statistics

In [ ]:
# Create 4 by 2 DataFrame with [[2.4, np.nan], [6.3, -5.4], [np.nan, np.nan], and [0.75, -1.3]]
# Set index name as ["a", "b", "c", "d"] and column names as ["one", "two"]
data = [[2.4, np.nan],
        [6.3, -5.4],
        [np.nan, np.nan],
        [0.75, -1.3]]
df = pd.DataFrame(data, index=["a", "b", "c", "d"], columns=["one", "two"])

print(df)

    one  two
a  2.40  NaN
b  6.30 -5.4
c   NaN  NaN
d  0.75 -1.3

In [ ]:
# Return the sum of the values over the axis
df.sum(axis=0)

one    9.45
two   -6.70
dtype: float64

In [ ]:
# Return the sum of the values over the axis=1
df.sum(axis=1)

a    2.40
b    0.90
c    0.00
d   -0.55
dtype: float64

In [ ]:
# Return the mean of the values over the axis
df.mean(axis=1)

a    2.400
b    0.450
c      NaN
d   -0.275
dtype: float64

In [ ]:
# Return index of first occurrence of maximum over the axis
df.idxmax(axis=0)

one    b
two    d
dtype: object

In [ ]:
# Return index of first occurrence of minimum over the axis
df.idxmin(axis=1)

<ipython-input-32-f08d2127d3bb>:2: FutureWarning: The behavior of DataFrame.idxmin with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  df.idxmin(axis=1)

a    one
b    two
c    NaN
d    two
dtype: object

In [ ]:
# Return cumulative sum over a DataFrame or Series axis
df.cumsum()
# axis=0으로 동작함

    one  two
a  2.40  NaN
b  8.70 -5.4
c   NaN  NaN
d  9.45 -6.7

In [ ]:
# Generate descriptive statistics
df.describe()

         one       two
count  3.000  2.000000
mean   3.150 -3.350000
std    2.850  2.899138
min    0.750 -5.400000
25%    1.575 -4.375000
50%    2.400 -3.350000
75%    4.350 -2.325000
max    6.300 -1.300000

### Indexing & selection & Filtering in Pandas
* DataFrame indexing

In [ ]:
# Make a DataFrame with 16 consecutive integers of size (4, 4) starting at 0
# Set the index as ["London", "Paris", "Berlin", "Istanbul"]
# Set the column as ["one", "two", "three", "four"]

# np.arange(16) = [0, 1, 2, 3, ..., 15]

data=pd.DataFrame(
    np.arange(16).reshape(4,4),
    index=["London", "Paris", "Berlin", "Istanbul"],
    columns=["one", "two", "three", "four"])

print(data)

          one  two  three  four
London      0    1      2     3
Paris       4    5      6     7
Berlin      8    9     10    11
Istanbul   12   13     14    15

In [ ]:
# Print the second column data
print(data["two"])

London       1
Paris        5
Berlin       9
Istanbul    13
Name: two, dtype: int64

In [ ]:
# Print the second and third columns data
print(data[["two", "three"]])

          two  three
London      1      2
Paris       5      6
Berlin      9     10
Istanbul   13     14

In [ ]:
# Print rows that the value of last column is greater than 5
print(data[data["four"] > 5])

          one  two  three  four
Paris       4    5      6     7
Berlin      8    9     10    11
Istanbul   12   13     14    15

In [ ]:
# Change the value where each data is smaller than 5
data[data < 5] = 10

print(data)

          one  two  three  four
London     10   10     10    10
Paris      10    5      6     7
Berlin      8    9     10    11
Istanbul   12   13     14    15

* Selecting with iloc and loc

In [ ]:
# Print the rows with index 1
data.iloc[1]

one      10
two       5
three     6
four      7
Name: Paris, dtype: int64

In [ ]:
# Print the data with row index with 1 and column index with [1, 2, 3]
data.iloc[1, [1, 2, 3]]

two      5
three    6
four     7
Name: Paris, dtype: int64

In [ ]:
# Print the data with row index with [1, 3] and column index with [1, 2, 3]
data.iloc[[1, 3], [1, 2, 3]]

          two  three  four
Paris       5      6     7
Istanbul   13     14    15

In [ ]:
# Print the data with Paris row and ["one","two"] columns
data.loc["Paris", ["one", "two"]]

one    10
two     5
Name: Paris, dtype: int64

### Combininig & Merging Datasets in Pandas
* Joining DataFrame

In [ ]:
# Create the DataFrame called d1
# key: ["a", "b", "c", "c", "d", "e"]
# num1: [0, 1, 2, 3, 4, 5]
d1 = pd.DataFrame(
    {
        "key": ["a", "b", "c", "c", "d", "e"],
        "num1": [0, 1, 2, 3, 4, 5]
    }
)

# Create the DataFrame called d2
# key: ["b", "c", "e", "f"]
# num2: [0, 1, 2, 3]
d2 = pd.DataFrame(
    {
        "key": ["b", "c", "e", "f"],
        "num2": [0, 1, 2, 3]
    }
)

print(d1)
print(d2)

  key  num1
0   a     0
1   b     1
2   c     2
3   c     3
4   d     4
5   e     5
  key  num2
0   b     0
1   c     1
2   e     2
3   f     3

In [ ]:
pd.merge(d1, d2)
# 공통된 column이 없으면 에러

  key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2

In [ ]:
pd.merge(d1, d2, on="key")

  key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2

In [ ]:
# Create the DataFrame called d3
# key1: ["a", "b", "c", "c", "d", "e"]
# num1: [0, 1, 2, 3, 4, 5]
d3 = pd.DataFrame(
    {
        "key1": ["a", "b", "c", "c", "d", "e"],
        "num1": [0, 1, 2, 3, 4, 5]
    }
)

# Create the DataFrame called d4
# key2: ["b", "c", "e", "f"]
# num2: [0, 1, 2, 3]
d4 = pd.DataFrame(
    {
        "key2": ["b", "c", "e", "f"],
        "num2": [0, 1, 2, 3]
    }
)

print(d3)
print(d4)

  key1  num1
0    a     0
1    b     1
2    c     2
3    c     3
4    d     4
5    e     5
  key2  num2
0    b     0
1    c     1
2    e     2
3    f     3

In [ ]:
pd.merge(d3, d4, left_on="key1", right_on="key2")

  key1  num1 key2  num2
0    b     1    b     0
1    c     2    c     1
2    c     3    c     1
3    e     5    e     2

In [ ]:
 # 합집합
 # d1, d2의 키 값 중 하나라도 존재하면 모두 포함
 # 공통되지 않는 키 값의 경우 NaN
pd.merge(d1, d2, how="outer")

  key  num1  num2
0   a   0.0   NaN
1   b   1.0   0.0
2   c   2.0   1.0
3   c   3.0   1.0
4   d   4.0   NaN
5   e   5.0   2.0
6   f   NaN   3.0

In [ ]:
# 왼쪽 데이터 프레임 기준으로 왼쪽에 맞춰 합치기
# d1의 모든 값을 유지하고, d2에서 일치하는 값이 있는 경우만 결합
# d2에 일치하는 값이 없으면 NaN으로 채움
pd.merge(d1,d2,how="left")

  key  num1  num2
0   a     0   NaN
1   b     1   0.0
2   c     2   1.0
3   c     3   1.0
4   d     4   NaN
5   e     5   2.0

In [ ]:
# 오른쪽 데이터 프레임 기준으로 오른쪽에 맞춰 합치기.
# d2의 모든 키 값이 유지되고, d1에서 일치하는 값이 있는 경우만 결합
# d1에 일치하는 값이 없으면 NaN으로 채움
pd.merge(d1,d2,how="right")

  key  num1  num2
0   b   1.0     0
1   c   2.0     1
2   c   3.0     1
3   e   5.0     2
4   f   NaN     3

In [ ]:
# 교집합. 두 DataFrame에서 공통되는 키 값만 병합함
pd.merge(d1, d2, how='inner')

  key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2

### Missing Data in Pandas

In [ ]:
from numpy import nan as NA

# Create a 3 by 3DataFrame with [[1,2,3],[4,NA,5],[NA,NA,NA]]
df = pd.DataFrame([[1,2,3],
                   [4,NA,5],
                   [NA,NA,NA]])

print(df)

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0
2  NaN  NaN  NaN

In [ ]:
# Remove rows containing NaN values
print(df.dropna())

     0    1    2
0  1.0  2.0  3.0

In [ ]:
# Remove rows containing NaN values when all the values are NaN
print(df.dropna(how="all"))

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0

In [ ]:
# Fill NA values
# NA in the first column with 15
# NA in the second column with 25
# NA in the third column with 35
print(df.fillna({0:15, 1:25, 2:35}))

      0     1     2
0   1.0   2.0   3.0
1   4.0  25.0   5.0
2  15.0  25.0  35.0